### ISSUE TITLE
[AIELLO] entregar SP solicitado para su aplicacion con Recaudacion Neta y A cobrar del control de fiado

### ISSUE THREAD

**Issue by leaguidi** [grupo-elementum/.github#18]
se paso todo el detalle por whatsapp

**Comment by MatiasGuidi** [comment]
se generaron los SPs

WS_GET_FIADO_REPARTO 1,'13/12/2024',0
WS_GET_RECAUDACION_NETA 1,'12/12/2024','12/12/2024'

se enviaron para que puedan comenzar a utilizarlos
